# from "edge" tag on 2025/07/28
FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf@sha256:5992e24a88b1c0b2a7338863eb12075fa0679c04ae2dd519e480d294a748a51a

RUN dpkg --add-architecture arm && \
    apt-get update && \
    apt-get install -y apt-transport-https wget gnupg2 && \
    (wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -) && \
    printf "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main\ndeb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -y llvm-12-dev libclang-12-dev clang-12 libc++-12-dev && \
    apt-get purge -y apt-transport-https wget

ENV RUST_LOG=bindgen
