name: ci

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-runner-set
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          python3 -c 'import glob, json; files=glob.glob("Dockerfile.*"); images=list(map(lambda f: {"file":f, "arch":f[11:]}, files)); print("::set-output name=matrix::"+json.dumps({"image": images}))'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  builds:
    name: Build zettascaletech/rust-cross:${{ matrix.image.arch }}
    needs: prepare
    runs-on: ubuntu-runner-set
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build zettascaletech/rust-cross:${{ matrix.image.arch }} from ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: ${{ matrix.image.file }}
          tags: zettascaletech/rust-cross:${{ matrix.image.arch }}
